apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: webserver-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: apache
        image: php:apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
      volumes:
      - name: html-volume
        configMap:
          name: webserver-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: webserver-config
data:
  index.php: |
    <?php
    echo "Serwer działa na adresie IP: " . $_SERVER['SERVER_ADDR'];
    ?>

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: webserver-service
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
